name: Deploy Project to Surge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
       node-version: '12'
      # Step to install Surge
    - name: Installing Surge
      run: npm install --global surge
      
      # Deploy App to Surge
    - name: Deploying Project to Surge
      run: surge ./ mumraizbabar_portfolio.surge.sh 
    
    
